### ISSUE TITLE
About the results

### ISSUE THREAD

**Issue by wlaamaa** [Vincent-ZHQ/CA-MSER#18]
Hello, excuse me, are the average UA and WA results of the source code running the results given in the paper?

**Comment by Vincent-ZHQ** [comment]
Yeah. The reported results are the averaged performance of the N-fold cross-validation strategy.

**Comment by wlaamaa** [comment]
Thank you for your answer, but the results of my operation, WA and UA are only 68.3 and 68.9 respectively, which are lower than yours. What is the reason? 

> Yeah. The reported results are the averaged performance of the N-fold cross-validation strategy.

**Comment by Vincent-ZHQ** [comment]
I do not know. It may be due to the parameter or environment difference. When I was working on this project, I could get the paper's results relatively stably given the code parameters. After all, this was a job two years ago. So I can only suggest using the provided parameters in your reproduction.

**Comment by wlaamaa** [comment]
Thank you for your answer.
